---
all:
  children:
    proxmox:
      hosts:
        pve1:
          ansible_host: 192.168.16.7
          ansible_user: root
          ansible_port: 22
          ansible_python_interpreter: /usr/bin/python3
      vars:
        # Proxmox API settings
        proxmox_api_host: "192.168.16.7"
        proxmox_api_user: "root@pam"
        # proxmox_api_password: "{{ vault_proxmox_password }}"
        # proxmox_api_token_id: "{{ vault_proxmox_token_id }}"
        # proxmox_api_token_secret: "{{ vault_proxmox_token_secret }}"

        # Common settings
        timezone: "America/New_York"
        ntp_servers:
          - "pool.ntp.org"
          - "time.nist.gov"
